AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless backend for blinky app.
Parameters:
  TopicName:
    Type: String
    Default: ''
Resources:
  BlinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.6
      # `sam package` will upload the code at this path to S3 and update the CodeUri
      CodeUri: blinky/
      Environment:
        Variables:
          IOT_TOPIC: {Ref: TopicName}
      Policies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: iot:Publish
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/${TopicName}
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        Blink:
          Type: Api
          Properties:
            Path: /blink
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlinkyApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/blink/"
  BlinkFunction:
    Value: !GetAtt BlinkFunction.Arn
  BlinkFunctionIamRole:
    Value: !GetAtt BlinkFunctionRole.Arn
