Parameters:
  ButtonSerialNumber:
    Type: String
  TopicName:
    Type: String
Resources:
  MqttRepublishRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        RuleDisabled: false
        Sql:
          Fn::Sub: SELECT * FROM 'iotbutton/${ButtonSerialNumber}'
        Actions:
          -
            Republish:
              RoleArn:
                Fn::GetAtt:
                  - MqttRepublishRole
                  - Arn
              Topic:
                Ref: TopicName
  MqttRepublishRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: iot-light-publisher
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action: iot:Publish
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/${TopicName}
